package com.gouhai.baoshan.webservice.client.organization;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-24T09:57:07.701+08:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "http://wsaf.wicresoft.com/", name = "OrganizationServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface OrganizationServiceSoap {

    /**
     * 检验用户是否在权限组中
     */
    @WebResult(name = "IsUserByIDInGroupResult", targetNamespace = "http://wsaf.wicresoft.com/")
    @RequestWrapper(localName = "IsUserByIDInGroup", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.IsUserByIDInGroup")
    @WebMethod(operationName = "IsUserByIDInGroup", action = "http://wsaf.wicresoft.com/IsUserByIDInGroup")
    @ResponseWrapper(localName = "IsUserByIDInGroupResponse", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.IsUserByIDInGroupResponse")
    public boolean isUserByIDInGroup(
        @WebParam(name = "userID", targetNamespace = "http://wsaf.wicresoft.com/")
        java.lang.String userID,
        @WebParam(name = "groupID", targetNamespace = "http://wsaf.wicresoft.com/")
        java.lang.String groupID
    );

    /**
     * 获取用户获得角色的方式（从角色到用户的路径）
     */
    @WebResult(name = "GetRoleUserByIDPathResult", targetNamespace = "http://wsaf.wicresoft.com/")
    @RequestWrapper(localName = "GetRoleUserByIDPath", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.GetRoleUserByIDPath")
    @WebMethod(operationName = "GetRoleUserByIDPath", action = "http://wsaf.wicresoft.com/GetRoleUserByIDPath")
    @ResponseWrapper(localName = "GetRoleUserByIDPathResponse", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.GetRoleUserByIDPathResponse")
    public java.lang.String getRoleUserByIDPath(
        @WebParam(name = "roleID", targetNamespace = "http://wsaf.wicresoft.com/")
        java.lang.String roleID,
        @WebParam(name = "userID", targetNamespace = "http://wsaf.wicresoft.com/")
        java.lang.String userID
    );

    /**
     * 获取部门下的所有部门，recursive表示是否包含下层部门
     */
    @WebResult(name = "GetDepartmentInfoListByParentDepartmentResult", targetNamespace = "http://wsaf.wicresoft.com/")
    @RequestWrapper(localName = "GetDepartmentInfoListByParentDepartment", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.GetDepartmentInfoListByParentDepartment")
    @WebMethod(operationName = "GetDepartmentInfoListByParentDepartment", action = "http://wsaf.wicresoft.com/GetDepartmentInfoListByParentDepartment")
    @ResponseWrapper(localName = "GetDepartmentInfoListByParentDepartmentResponse", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.GetDepartmentInfoListByParentDepartmentResponse")
    public java.lang.String getDepartmentInfoListByParentDepartment(
        @WebParam(name = "parentDepartmentID", targetNamespace = "http://wsaf.wicresoft.com/")
        java.lang.String parentDepartmentID,
        @WebParam(name = "recursive", targetNamespace = "http://wsaf.wicresoft.com/")
        boolean recursive
    );

    /**
     * 在系统中搜索部门信息
     */
    @WebResult(name = "SearchDepartmentResult", targetNamespace = "http://wsaf.wicresoft.com/")
    @RequestWrapper(localName = "SearchDepartment", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.SearchDepartment")
    @WebMethod(operationName = "SearchDepartment", action = "http://wsaf.wicresoft.com/SearchDepartment")
    @ResponseWrapper(localName = "SearchDepartmentResponse", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.SearchDepartmentResponse")
    public java.lang.String searchDepartment(
        @WebParam(name = "conditionXml", targetNamespace = "http://wsaf.wicresoft.com/")
        java.lang.String conditionXml
    );

    /**
     * 在系统中搜索用户信息
     */
    @WebResult(name = "SearchUserResult", targetNamespace = "http://wsaf.wicresoft.com/")
    @RequestWrapper(localName = "SearchUser", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.SearchUser")
    @WebMethod(operationName = "SearchUser", action = "http://wsaf.wicresoft.com/SearchUser")
    @ResponseWrapper(localName = "SearchUserResponse", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.SearchUserResponse")
    public java.lang.String searchUser(
        @WebParam(name = "conditionXml", targetNamespace = "http://wsaf.wicresoft.com/")
        java.lang.String conditionXml
    );

    /**
     * 检验部门是否在部门中
     */
    @WebResult(name = "IsDepartmentInDepartmentResult", targetNamespace = "http://wsaf.wicresoft.com/")
    @RequestWrapper(localName = "IsDepartmentInDepartment", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.IsDepartmentInDepartment")
    @WebMethod(operationName = "IsDepartmentInDepartment", action = "http://wsaf.wicresoft.com/IsDepartmentInDepartment")
    @ResponseWrapper(localName = "IsDepartmentInDepartmentResponse", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.IsDepartmentInDepartmentResponse")
    public boolean isDepartmentInDepartment(
        @WebParam(name = "offspringDepartmentID", targetNamespace = "http://wsaf.wicresoft.com/")
        java.lang.String offspringDepartmentID,
        @WebParam(name = "ancestorDepartmentID", targetNamespace = "http://wsaf.wicresoft.com/")
        java.lang.String ancestorDepartmentID,
        @WebParam(name = "recursive", targetNamespace = "http://wsaf.wicresoft.com/")
        boolean recursive
    );

    /**
     * 在系统中搜索角色信息
     */
    @WebResult(name = "SearchRoleResult", targetNamespace = "http://wsaf.wicresoft.com/")
    @RequestWrapper(localName = "SearchRole", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.SearchRole")
    @WebMethod(operationName = "SearchRole", action = "http://wsaf.wicresoft.com/SearchRole")
    @ResponseWrapper(localName = "SearchRoleResponse", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.SearchRoleResponse")
    public java.lang.String searchRole(
        @WebParam(name = "conditionXml", targetNamespace = "http://wsaf.wicresoft.com/")
        java.lang.String conditionXml
    );

    /**
     * 检验用户是否在角色中
     */
    @WebResult(name = "IsUserByNameInRoleResult", targetNamespace = "http://wsaf.wicresoft.com/")
    @RequestWrapper(localName = "IsUserByNameInRole", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.IsUserByNameInRole")
    @WebMethod(operationName = "IsUserByNameInRole", action = "http://wsaf.wicresoft.com/IsUserByNameInRole")
    @ResponseWrapper(localName = "IsUserByNameInRoleResponse", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.IsUserByNameInRoleResponse")
    public boolean isUserByNameInRole(
        @WebParam(name = "userName", targetNamespace = "http://wsaf.wicresoft.com/")
        java.lang.String userName,
        @WebParam(name = "roleID", targetNamespace = "http://wsaf.wicresoft.com/")
        java.lang.String roleID
    );

    /**
     * 获取部门下的全体用户信息，recursive表示是否包含下层部门
     */
    @WebResult(name = "GetUserInfoListByRoleResult", targetNamespace = "http://wsaf.wicresoft.com/")
    @RequestWrapper(localName = "GetUserInfoListByRole", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.GetUserInfoListByRole")
    @WebMethod(operationName = "GetUserInfoListByRole", action = "http://wsaf.wicresoft.com/GetUserInfoListByRole")
    @ResponseWrapper(localName = "GetUserInfoListByRoleResponse", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.GetUserInfoListByRoleResponse")
    public java.lang.String getUserInfoListByRole(
        @WebParam(name = "roleID", targetNamespace = "http://wsaf.wicresoft.com/")
        java.lang.String roleID,
        @WebParam(name = "recursive", targetNamespace = "http://wsaf.wicresoft.com/")
        boolean recursive
    );

    /**
     * 获取部门在部门中的位置（从部门到用户的路径）
     */
    @WebResult(name = "GetDepartmentDepartmentPathResult", targetNamespace = "http://wsaf.wicresoft.com/")
    @RequestWrapper(localName = "GetDepartmentDepartmentPath", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.GetDepartmentDepartmentPath")
    @WebMethod(operationName = "GetDepartmentDepartmentPath", action = "http://wsaf.wicresoft.com/GetDepartmentDepartmentPath")
    @ResponseWrapper(localName = "GetDepartmentDepartmentPathResponse", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.GetDepartmentDepartmentPathResponse")
    public java.lang.String getDepartmentDepartmentPath(
        @WebParam(name = "ancestorDepartmentID", targetNamespace = "http://wsaf.wicresoft.com/")
        java.lang.String ancestorDepartmentID,
        @WebParam(name = "offspringDepartmentID", targetNamespace = "http://wsaf.wicresoft.com/")
        java.lang.String offspringDepartmentID
    );

    /**
     * 获取全体用户信息
     */
    @WebResult(name = "GetUserInfoListResult", targetNamespace = "http://wsaf.wicresoft.com/")
    @RequestWrapper(localName = "GetUserInfoList", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.GetUserInfoList")
    @WebMethod(operationName = "GetUserInfoList", action = "http://wsaf.wicresoft.com/GetUserInfoList")
    @ResponseWrapper(localName = "GetUserInfoListResponse", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.GetUserInfoListResponse")
    public java.lang.String getUserInfoList();

    /**
     * 获取全体团队信息
     */
    @WebResult(name = "GetGroupInfoListResult", targetNamespace = "http://wsaf.wicresoft.com/")
    @RequestWrapper(localName = "GetGroupInfoList", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.GetGroupInfoList")
    @WebMethod(operationName = "GetGroupInfoList", action = "http://wsaf.wicresoft.com/GetGroupInfoList")
    @ResponseWrapper(localName = "GetGroupInfoListResponse", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.GetGroupInfoListResponse")
    public java.lang.String getGroupInfoList();

    /**
     * 在部门下搜索用户，recursive表示是否包含下层部门
     */
    @WebResult(name = "SearchUserByDepartmentResult", targetNamespace = "http://wsaf.wicresoft.com/")
    @RequestWrapper(localName = "SearchUserByDepartment", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.SearchUserByDepartment")
    @WebMethod(operationName = "SearchUserByDepartment", action = "http://wsaf.wicresoft.com/SearchUserByDepartment")
    @ResponseWrapper(localName = "SearchUserByDepartmentResponse", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.SearchUserByDepartmentResponse")
    public java.lang.String searchUserByDepartment(
        @WebParam(name = "departmentID", targetNamespace = "http://wsaf.wicresoft.com/")
        java.lang.String departmentID,
        @WebParam(name = "conditionXml", targetNamespace = "http://wsaf.wicresoft.com/")
        java.lang.String conditionXml,
        @WebParam(name = "recursive", targetNamespace = "http://wsaf.wicresoft.com/")
        boolean recursive
    );

    /**
     * 获取部门下的全体用户信息，recursive表示是否包含下层部门
     */
    @WebResult(name = "GetUserInfoListByDepartmentResult", targetNamespace = "http://wsaf.wicresoft.com/")
    @RequestWrapper(localName = "GetUserInfoListByDepartment", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.GetUserInfoListByDepartment")
    @WebMethod(operationName = "GetUserInfoListByDepartment", action = "http://wsaf.wicresoft.com/GetUserInfoListByDepartment")
    @ResponseWrapper(localName = "GetUserInfoListByDepartmentResponse", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.GetUserInfoListByDepartmentResponse")
    public java.lang.String getUserInfoListByDepartment(
        @WebParam(name = "parentDepartmentID", targetNamespace = "http://wsaf.wicresoft.com/")
        java.lang.String parentDepartmentID,
        @WebParam(name = "recursive", targetNamespace = "http://wsaf.wicresoft.com/")
        boolean recursive
    );

    /**
     * 获取用户绑定的全部角色信息
     */
    @WebResult(name = "GetRoleInfoListByUserIDResult", targetNamespace = "http://wsaf.wicresoft.com/")
    @RequestWrapper(localName = "GetRoleInfoListByUserID", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.GetRoleInfoListByUserID")
    @WebMethod(operationName = "GetRoleInfoListByUserID", action = "http://wsaf.wicresoft.com/GetRoleInfoListByUserID")
    @ResponseWrapper(localName = "GetRoleInfoListByUserIDResponse", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.GetRoleInfoListByUserIDResponse")
    public java.lang.String getRoleInfoListByUserID(
        @WebParam(name = "userID", targetNamespace = "http://wsaf.wicresoft.com/")
        java.lang.String userID
    );

    /**
     * 根据用户名获得用户信息
     */
    @WebResult(name = "GetUserInfoByNameResult", targetNamespace = "http://wsaf.wicresoft.com/")
    @RequestWrapper(localName = "GetUserInfoByName", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.GetUserInfoByName")
    @WebMethod(operationName = "GetUserInfoByName", action = "http://wsaf.wicresoft.com/GetUserInfoByName")
    @ResponseWrapper(localName = "GetUserInfoByNameResponse", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.GetUserInfoByNameResponse")
    public java.lang.String getUserInfoByName(
        @WebParam(name = "userName", targetNamespace = "http://wsaf.wicresoft.com/")
        java.lang.String userName
    );

    /**
     * 获取用户绑定的全部角色信息
     */
    @WebResult(name = "GetRoleInfoListByUserNameResult", targetNamespace = "http://wsaf.wicresoft.com/")
    @RequestWrapper(localName = "GetRoleInfoListByUserName", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.GetRoleInfoListByUserName")
    @WebMethod(operationName = "GetRoleInfoListByUserName", action = "http://wsaf.wicresoft.com/GetRoleInfoListByUserName")
    @ResponseWrapper(localName = "GetRoleInfoListByUserNameResponse", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.GetRoleInfoListByUserNameResponse")
    public java.lang.String getRoleInfoListByUserName(
        @WebParam(name = "userName", targetNamespace = "http://wsaf.wicresoft.com/")
        java.lang.String userName
    );

    /**
     * 获取团队绑定的全部角色信息
     */
    @WebResult(name = "GetRoleInfoListByGroupResult", targetNamespace = "http://wsaf.wicresoft.com/")
    @RequestWrapper(localName = "GetRoleInfoListByGroup", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.GetRoleInfoListByGroup")
    @WebMethod(operationName = "GetRoleInfoListByGroup", action = "http://wsaf.wicresoft.com/GetRoleInfoListByGroup")
    @ResponseWrapper(localName = "GetRoleInfoListByGroupResponse", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.GetRoleInfoListByGroupResponse")
    public java.lang.String getRoleInfoListByGroup(
        @WebParam(name = "groupID", targetNamespace = "http://wsaf.wicresoft.com/")
        java.lang.String groupID
    );

    /**
     * 获取全体角色信息
     */
    @WebResult(name = "GetRoleInfoListResult", targetNamespace = "http://wsaf.wicresoft.com/")
    @RequestWrapper(localName = "GetRoleInfoList", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.GetRoleInfoList")
    @WebMethod(operationName = "GetRoleInfoList", action = "http://wsaf.wicresoft.com/GetRoleInfoList")
    @ResponseWrapper(localName = "GetRoleInfoListResponse", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.GetRoleInfoListResponse")
    public java.lang.String getRoleInfoList();

    /**
     * 获取角色信息
     */
    @WebResult(name = "GetRoleInfoResult", targetNamespace = "http://wsaf.wicresoft.com/")
    @RequestWrapper(localName = "GetRoleInfo", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.GetRoleInfo")
    @WebMethod(operationName = "GetRoleInfo", action = "http://wsaf.wicresoft.com/GetRoleInfo")
    @ResponseWrapper(localName = "GetRoleInfoResponse", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.GetRoleInfoResponse")
    public java.lang.String getRoleInfo(
        @WebParam(name = "roleID", targetNamespace = "http://wsaf.wicresoft.com/")
        java.lang.String roleID
    );

    /**
     * 检验用户是否在部门中
     */
    @WebResult(name = "IsUserByIDInDepartmentResult", targetNamespace = "http://wsaf.wicresoft.com/")
    @RequestWrapper(localName = "IsUserByIDInDepartment", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.IsUserByIDInDepartment")
    @WebMethod(operationName = "IsUserByIDInDepartment", action = "http://wsaf.wicresoft.com/IsUserByIDInDepartment")
    @ResponseWrapper(localName = "IsUserByIDInDepartmentResponse", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.IsUserByIDInDepartmentResponse")
    public boolean isUserByIDInDepartment(
        @WebParam(name = "userID", targetNamespace = "http://wsaf.wicresoft.com/")
        java.lang.String userID,
        @WebParam(name = "departmentID", targetNamespace = "http://wsaf.wicresoft.com/")
        java.lang.String departmentID
    );

    /**
     * 根据用户ID获得用户信息
     */
    @WebResult(name = "GetUserInfoByIDResult", targetNamespace = "http://wsaf.wicresoft.com/")
    @RequestWrapper(localName = "GetUserInfoByID", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.GetUserInfoByID")
    @WebMethod(operationName = "GetUserInfoByID", action = "http://wsaf.wicresoft.com/GetUserInfoByID")
    @ResponseWrapper(localName = "GetUserInfoByIDResponse", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.GetUserInfoByIDResponse")
    public java.lang.String getUserInfoByID(
        @WebParam(name = "userID", targetNamespace = "http://wsaf.wicresoft.com/")
        java.lang.String userID
    );

    /**
     * 在部门下搜索部门，recursive表示是否包含下层部门
     */
    @WebResult(name = "SearchDepartmentByParentDepartmentResult", targetNamespace = "http://wsaf.wicresoft.com/")
    @RequestWrapper(localName = "SearchDepartmentByParentDepartment", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.SearchDepartmentByParentDepartment")
    @WebMethod(operationName = "SearchDepartmentByParentDepartment", action = "http://wsaf.wicresoft.com/SearchDepartmentByParentDepartment")
    @ResponseWrapper(localName = "SearchDepartmentByParentDepartmentResponse", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.SearchDepartmentByParentDepartmentResponse")
    public java.lang.String searchDepartmentByParentDepartment(
        @WebParam(name = "parentDepartmentID", targetNamespace = "http://wsaf.wicresoft.com/")
        java.lang.String parentDepartmentID,
        @WebParam(name = "conditionXml", targetNamespace = "http://wsaf.wicresoft.com/")
        java.lang.String conditionXml,
        @WebParam(name = "recursive", targetNamespace = "http://wsaf.wicresoft.com/")
        boolean recursive
    );

    /**
     * 获取全体部门信息
     */
    @WebResult(name = "GetDepartmentInfoListResult", targetNamespace = "http://wsaf.wicresoft.com/")
    @RequestWrapper(localName = "GetDepartmentInfoList", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.GetDepartmentInfoList")
    @WebMethod(operationName = "GetDepartmentInfoList", action = "http://wsaf.wicresoft.com/GetDepartmentInfoList")
    @ResponseWrapper(localName = "GetDepartmentInfoListResponse", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.GetDepartmentInfoListResponse")
    public java.lang.String getDepartmentInfoList();

    /**
     * 检验用户是否在部门中
     */
    @WebResult(name = "IsUserByNameInDepartmentResult", targetNamespace = "http://wsaf.wicresoft.com/")
    @RequestWrapper(localName = "IsUserByNameInDepartment", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.IsUserByNameInDepartment")
    @WebMethod(operationName = "IsUserByNameInDepartment", action = "http://wsaf.wicresoft.com/IsUserByNameInDepartment")
    @ResponseWrapper(localName = "IsUserByNameInDepartmentResponse", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.IsUserByNameInDepartmentResponse")
    public boolean isUserByNameInDepartment(
        @WebParam(name = "userName", targetNamespace = "http://wsaf.wicresoft.com/")
        java.lang.String userName,
        @WebParam(name = "departmentID", targetNamespace = "http://wsaf.wicresoft.com/")
        java.lang.String departmentID
    );

    /**
     * 获取部门下所有的团队信息，recursive表示是否包含下层部门
     */
    @WebResult(name = "GetGroupInfoListByDepartmentResult", targetNamespace = "http://wsaf.wicresoft.com/")
    @RequestWrapper(localName = "GetGroupInfoListByDepartment", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.GetGroupInfoListByDepartment")
    @WebMethod(operationName = "GetGroupInfoListByDepartment", action = "http://wsaf.wicresoft.com/GetGroupInfoListByDepartment")
    @ResponseWrapper(localName = "GetGroupInfoListByDepartmentResponse", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.GetGroupInfoListByDepartmentResponse")
    public java.lang.String getGroupInfoListByDepartment(
        @WebParam(name = "departmentID", targetNamespace = "http://wsaf.wicresoft.com/")
        java.lang.String departmentID,
        @WebParam(name = "recursive", targetNamespace = "http://wsaf.wicresoft.com/")
        boolean recursive
    );

    /**
     * 获取部门信息
     */
    @WebResult(name = "GetDepartmentInfoResult", targetNamespace = "http://wsaf.wicresoft.com/")
    @RequestWrapper(localName = "GetDepartmentInfo", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.GetDepartmentInfo")
    @WebMethod(operationName = "GetDepartmentInfo", action = "http://wsaf.wicresoft.com/GetDepartmentInfo")
    @ResponseWrapper(localName = "GetDepartmentInfoResponse", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.GetDepartmentInfoResponse")
    public java.lang.String getDepartmentInfo(
        @WebParam(name = "departmentID", targetNamespace = "http://wsaf.wicresoft.com/")
        java.lang.String departmentID
    );

    /**
     * 获取用户在部门中的位置（从部门到用户的路径
     */
    @WebResult(name = "GetDepartmentUserByIDPathResult", targetNamespace = "http://wsaf.wicresoft.com/")
    @RequestWrapper(localName = "GetDepartmentUserByIDPath", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.GetDepartmentUserByIDPath")
    @WebMethod(operationName = "GetDepartmentUserByIDPath", action = "http://wsaf.wicresoft.com/GetDepartmentUserByIDPath")
    @ResponseWrapper(localName = "GetDepartmentUserByIDPathResponse", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.GetDepartmentUserByIDPathResponse")
    public java.lang.String getDepartmentUserByIDPath(
        @WebParam(name = "departmentID", targetNamespace = "http://wsaf.wicresoft.com/")
        java.lang.String departmentID,
        @WebParam(name = "userName", targetNamespace = "http://wsaf.wicresoft.com/")
        java.lang.String userName
    );

    /**
     * 检验用户是否在角色中
     */
    @WebResult(name = "IsUserByIDInRoleResult", targetNamespace = "http://wsaf.wicresoft.com/")
    @RequestWrapper(localName = "IsUserByIDInRole", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.IsUserByIDInRole")
    @WebMethod(operationName = "IsUserByIDInRole", action = "http://wsaf.wicresoft.com/IsUserByIDInRole")
    @ResponseWrapper(localName = "IsUserByIDInRoleResponse", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.IsUserByIDInRoleResponse")
    public boolean isUserByIDInRole(
        @WebParam(name = "userID", targetNamespace = "http://wsaf.wicresoft.com/")
        java.lang.String userID,
        @WebParam(name = "roleID", targetNamespace = "http://wsaf.wicresoft.com/")
        java.lang.String roleID
    );

    /**
     * 检验权限组是否在部门中
     */
    @WebResult(name = "IsGroupInDepartmentResult", targetNamespace = "http://wsaf.wicresoft.com/")
    @RequestWrapper(localName = "IsGroupInDepartment", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.IsGroupInDepartment")
    @WebMethod(operationName = "IsGroupInDepartment", action = "http://wsaf.wicresoft.com/IsGroupInDepartment")
    @ResponseWrapper(localName = "IsGroupInDepartmentResponse", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.IsGroupInDepartmentResponse")
    public boolean isGroupInDepartment(
        @WebParam(name = "groupID", targetNamespace = "http://wsaf.wicresoft.com/")
        java.lang.String groupID,
        @WebParam(name = "departmentID", targetNamespace = "http://wsaf.wicresoft.com/")
        java.lang.String departmentID
    );

    /**
     * 检验用户是否在权限组中
     */
    @WebResult(name = "IsUserByNameInGroupResult", targetNamespace = "http://wsaf.wicresoft.com/")
    @RequestWrapper(localName = "IsUserByNameInGroup", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.IsUserByNameInGroup")
    @WebMethod(operationName = "IsUserByNameInGroup", action = "http://wsaf.wicresoft.com/IsUserByNameInGroup")
    @ResponseWrapper(localName = "IsUserByNameInGroupResponse", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.IsUserByNameInGroupResponse")
    public boolean isUserByNameInGroup(
        @WebParam(name = "userName", targetNamespace = "http://wsaf.wicresoft.com/")
        java.lang.String userName,
        @WebParam(name = "groupID", targetNamespace = "http://wsaf.wicresoft.com/")
        java.lang.String groupID
    );

    /**
     * 获取团队下的全体用户信息
     */
    @WebResult(name = "GetUserInfoListByGroupResult", targetNamespace = "http://wsaf.wicresoft.com/")
    @RequestWrapper(localName = "GetUserInfoListByGroup", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.GetUserInfoListByGroup")
    @WebMethod(operationName = "GetUserInfoListByGroup", action = "http://wsaf.wicresoft.com/GetUserInfoListByGroup")
    @ResponseWrapper(localName = "GetUserInfoListByGroupResponse", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.GetUserInfoListByGroupResponse")
    public java.lang.String getUserInfoListByGroup(
        @WebParam(name = "groupID", targetNamespace = "http://wsaf.wicresoft.com/")
        java.lang.String groupID
    );

    /**
     * 获取用户在部门中的位置（从部门到用户的路径
     */
    @WebResult(name = "GetDepartmentUserByNamePathResult", targetNamespace = "http://wsaf.wicresoft.com/")
    @RequestWrapper(localName = "GetDepartmentUserByNamePath", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.GetDepartmentUserByNamePath")
    @WebMethod(operationName = "GetDepartmentUserByNamePath", action = "http://wsaf.wicresoft.com/GetDepartmentUserByNamePath")
    @ResponseWrapper(localName = "GetDepartmentUserByNamePathResponse", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.GetDepartmentUserByNamePathResponse")
    public java.lang.String getDepartmentUserByNamePath(
        @WebParam(name = "departmentID", targetNamespace = "http://wsaf.wicresoft.com/")
        java.lang.String departmentID,
        @WebParam(name = "userID", targetNamespace = "http://wsaf.wicresoft.com/")
        java.lang.String userID
    );

    /**
     * 获取用户获得角色的方式（从角色到用户的路径）
     */
    @WebResult(name = "GetRoleUserByNamePathResult", targetNamespace = "http://wsaf.wicresoft.com/")
    @RequestWrapper(localName = "GetRoleUserByNamePath", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.GetRoleUserByNamePath")
    @WebMethod(operationName = "GetRoleUserByNamePath", action = "http://wsaf.wicresoft.com/GetRoleUserByNamePath")
    @ResponseWrapper(localName = "GetRoleUserByNamePathResponse", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.GetRoleUserByNamePathResponse")
    public java.lang.String getRoleUserByNamePath(
        @WebParam(name = "roleID", targetNamespace = "http://wsaf.wicresoft.com/")
        java.lang.String roleID,
        @WebParam(name = "userName", targetNamespace = "http://wsaf.wicresoft.com/")
        java.lang.String userName
    );

    /**
     * 在应用中搜索角色
     */
    @WebResult(name = "SearchRoleByApplicationResult", targetNamespace = "http://wsaf.wicresoft.com/")
    @RequestWrapper(localName = "SearchRoleByApplication", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.SearchRoleByApplication")
    @WebMethod(operationName = "SearchRoleByApplication", action = "http://wsaf.wicresoft.com/SearchRoleByApplication")
    @ResponseWrapper(localName = "SearchRoleByApplicationResponse", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.SearchRoleByApplicationResponse")
    public java.lang.String searchRoleByApplication(
        @WebParam(name = "applicationID", targetNamespace = "http://wsaf.wicresoft.com/")
        java.lang.String applicationID,
        @WebParam(name = "conditionXml", targetNamespace = "http://wsaf.wicresoft.com/")
        java.lang.String conditionXml
    );

    /**
     * 检验权限组是否在角色中
     */
    @WebResult(name = "IsGroupInRoleResult", targetNamespace = "http://wsaf.wicresoft.com/")
    @RequestWrapper(localName = "IsGroupInRole", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.IsGroupInRole")
    @WebMethod(operationName = "IsGroupInRole", action = "http://wsaf.wicresoft.com/IsGroupInRole")
    @ResponseWrapper(localName = "IsGroupInRoleResponse", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.IsGroupInRoleResponse")
    public boolean isGroupInRole(
        @WebParam(name = "groupID", targetNamespace = "http://wsaf.wicresoft.com/")
        java.lang.String groupID,
        @WebParam(name = "roleID", targetNamespace = "http://wsaf.wicresoft.com/")
        java.lang.String roleID
    );

    /**
     * 获取某个应用的全部角色信息
     */
    @WebResult(name = "GetRoleInfoListByApplicationResult", targetNamespace = "http://wsaf.wicresoft.com/")
    @RequestWrapper(localName = "GetRoleInfoListByApplication", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.GetRoleInfoListByApplication")
    @WebMethod(operationName = "GetRoleInfoListByApplication", action = "http://wsaf.wicresoft.com/GetRoleInfoListByApplication")
    @ResponseWrapper(localName = "GetRoleInfoListByApplicationResponse", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.GetRoleInfoListByApplicationResponse")
    public java.lang.String getRoleInfoListByApplication(
        @WebParam(name = "applicationID", targetNamespace = "http://wsaf.wicresoft.com/")
        java.lang.String applicationID
    );

    /**
     * 获取团队信息
     */
    @WebResult(name = "GetGroupInfoResult", targetNamespace = "http://wsaf.wicresoft.com/")
    @RequestWrapper(localName = "GetGroupInfo", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.GetGroupInfo")
    @WebMethod(operationName = "GetGroupInfo", action = "http://wsaf.wicresoft.com/GetGroupInfo")
    @ResponseWrapper(localName = "GetGroupInfoResponse", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.GetGroupInfoResponse")
    public java.lang.String getGroupInfo(
        @WebParam(name = "groupID", targetNamespace = "http://wsaf.wicresoft.com/")
        java.lang.String groupID
    );

    /**
     * 在部门下搜索团队信息，recursive表示是否包含下层部门
     */
    @WebResult(name = "SearchGroupByDepartmentResult", targetNamespace = "http://wsaf.wicresoft.com/")
    @RequestWrapper(localName = "SearchGroupByDepartment", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.SearchGroupByDepartment")
    @WebMethod(operationName = "SearchGroupByDepartment", action = "http://wsaf.wicresoft.com/SearchGroupByDepartment")
    @ResponseWrapper(localName = "SearchGroupByDepartmentResponse", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.SearchGroupByDepartmentResponse")
    public java.lang.String searchGroupByDepartment(
        @WebParam(name = "departmentID", targetNamespace = "http://wsaf.wicresoft.com/")
        java.lang.String departmentID,
        @WebParam(name = "conditionXml", targetNamespace = "http://wsaf.wicresoft.com/")
        java.lang.String conditionXml,
        @WebParam(name = "recursive", targetNamespace = "http://wsaf.wicresoft.com/")
        boolean recursive
    );

    /**
     * 在系统中搜索团队信息
     */
    @WebResult(name = "SearchGroupResult", targetNamespace = "http://wsaf.wicresoft.com/")
    @RequestWrapper(localName = "SearchGroup", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.SearchGroup")
    @WebMethod(operationName = "SearchGroup", action = "http://wsaf.wicresoft.com/SearchGroup")
    @ResponseWrapper(localName = "SearchGroupResponse", targetNamespace = "http://wsaf.wicresoft.com/", className = "com.gouhai.baoshan.webservice.client.organization.SearchGroupResponse")
    public java.lang.String searchGroup(
        @WebParam(name = "conditionXml", targetNamespace = "http://wsaf.wicresoft.com/")
        java.lang.String conditionXml
    );
}
