
package com.gouhai.baoshan.webservice.client.application;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-24T09:55:17.165+08:00
 * Generated source version: 3.0.1
 * 
 */
public final class ApplicationsServiceSoap_ApplicationsServiceSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://wsaf.wicresoft.com/", "ApplicationsService");

    private ApplicationsServiceSoap_ApplicationsServiceSoap_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ApplicationsService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ApplicationsService ss = new ApplicationsService(wsdlURL, SERVICE_NAME);
        ApplicationsServiceSoap port = ss.getApplicationsServiceSoap();  
        
        {
        System.out.println("Invoking getLogs...");
        java.lang.String _getLogs_applicationID = "";
        java.lang.String _getLogs__return = port.getLogs(_getLogs_applicationID);
        System.out.println("getLogs.result=" + _getLogs__return);


        }
        {
        System.out.println("Invoking getServiceInfo...");
        java.lang.String _getServiceInfo_serviceID = "";
        java.lang.String _getServiceInfo__return = port.getServiceInfo(_getServiceInfo_serviceID);
        System.out.println("getServiceInfo.result=" + _getServiceInfo__return);


        }
        {
        System.out.println("Invoking getServiceInfoListByApplication...");
        java.lang.String _getServiceInfoListByApplication_applicationID = "";
        java.lang.String _getServiceInfoListByApplication__return = port.getServiceInfoListByApplication(_getServiceInfoListByApplication_applicationID);
        System.out.println("getServiceInfoListByApplication.result=" + _getServiceInfoListByApplication__return);


        }
        {
        System.out.println("Invoking getApplicationInfoListByProductID...");
        java.lang.String _getApplicationInfoListByProductID_productID = "";
        java.lang.String _getApplicationInfoListByProductID__return = port.getApplicationInfoListByProductID(_getApplicationInfoListByProductID_productID);
        System.out.println("getApplicationInfoListByProductID.result=" + _getApplicationInfoListByProductID__return);


        }
        {
        System.out.println("Invoking sendEvent...");
        java.lang.String _sendEvent_applicationID = "";
        java.lang.String _sendEvent_eventDefinitionID = "";
        java.lang.String _sendEvent_eventData = "";
        java.lang.String _sendEvent__return = port.sendEvent(_sendEvent_applicationID, _sendEvent_eventDefinitionID, _sendEvent_eventData);
        System.out.println("sendEvent.result=" + _sendEvent__return);


        }
        {
        System.out.println("Invoking checkApplication...");
        java.lang.String _checkApplication_applicationID = "";
        boolean _checkApplication__return = port.checkApplication(_checkApplication_applicationID);
        System.out.println("checkApplication.result=" + _checkApplication__return);


        }
        {
        System.out.println("Invoking getEventInfoListByApplication...");
        java.lang.String _getEventInfoListByApplication_applicationID = "";
        javax.xml.datatype.XMLGregorianCalendar _getEventInfoListByApplication_beginTime = null;
        javax.xml.datatype.XMLGregorianCalendar _getEventInfoListByApplication_endTime = null;
        java.lang.String _getEventInfoListByApplication__return = port.getEventInfoListByApplication(_getEventInfoListByApplication_applicationID, _getEventInfoListByApplication_beginTime, _getEventInfoListByApplication_endTime);
        System.out.println("getEventInfoListByApplication.result=" + _getEventInfoListByApplication__return);


        }
        {
        System.out.println("Invoking writeLog...");
        java.lang.String _writeLog_applicationID = "";
        javax.xml.datatype.XMLGregorianCalendar _writeLog_createTime = null;
        java.lang.String _writeLog_eventData = "";
        java.lang.String _writeLog_userID = "";
        java.lang.String _writeLog_userName = "";
        int _writeLog_eventID = 0;
        java.lang.String _writeLog_category = "";
        java.lang.String _writeLog_type = "";
        boolean _writeLog__return = port.writeLog(_writeLog_applicationID, _writeLog_createTime, _writeLog_eventData, _writeLog_userID, _writeLog_userName, _writeLog_eventID, _writeLog_category, _writeLog_type);
        System.out.println("writeLog.result=" + _writeLog__return);


        }
        {
        System.out.println("Invoking getApplicationConfigByKey...");
        java.lang.String _getApplicationConfigByKey_applicationID = "";
        java.lang.String _getApplicationConfigByKey_key = "";
        java.lang.String _getApplicationConfigByKey__return = port.getApplicationConfigByKey(_getApplicationConfigByKey_applicationID, _getApplicationConfigByKey_key);
        System.out.println("getApplicationConfigByKey.result=" + _getApplicationConfigByKey__return);


        }
        {
        System.out.println("Invoking searchLogs...");
        java.lang.String _searchLogs_applicationID = "";
        java.lang.String _searchLogs_conditionXml = "";
        java.lang.String _searchLogs__return = port.searchLogs(_searchLogs_applicationID, _searchLogs_conditionXml);
        System.out.println("searchLogs.result=" + _searchLogs__return);


        }
        {
        System.out.println("Invoking getApplicationInfo...");
        java.lang.String _getApplicationInfo_applicationID = "";
        java.lang.String _getApplicationInfo__return = port.getApplicationInfo(_getApplicationInfo_applicationID);
        System.out.println("getApplicationInfo.result=" + _getApplicationInfo__return);


        }
        {
        System.out.println("Invoking getApplicationConfig...");
        java.lang.String _getApplicationConfig_applicationID = "";
        java.lang.String _getApplicationConfig__return = port.getApplicationConfig(_getApplicationConfig_applicationID);
        System.out.println("getApplicationConfig.result=" + _getApplicationConfig__return);


        }
        {
        System.out.println("Invoking getPublicConfig...");
        java.lang.String _getPublicConfig_key = "";
        java.lang.String _getPublicConfig__return = port.getPublicConfig(_getPublicConfig_key);
        System.out.println("getPublicConfig.result=" + _getPublicConfig__return);


        }

        System.exit(0);
    }

}
