package com.gouhai.baoshan.webservice.client.application;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * 统一平台应用管理服务
 *
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-24T09:55:17.221+08:00
 * Generated source version: 3.0.1
 * 
 */
@WebServiceClient(name = "ApplicationsService", 
                  wsdlLocation = "http://12.118.2.172/Framework.WebService/ApplicationsService.asmx?wsdl",
                  targetNamespace = "http://wsaf.wicresoft.com/") 
public class ApplicationsService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://wsaf.wicresoft.com/", "ApplicationsService");
    public final static QName ApplicationsServiceSoap = new QName("http://wsaf.wicresoft.com/", "ApplicationsServiceSoap");
    public final static QName ApplicationsServiceSoap12 = new QName("http://wsaf.wicresoft.com/", "ApplicationsServiceSoap12");
    static {
        URL url = null;
        try {
            url = new URL("http://12.118.2.172/Framework.WebService/ApplicationsService.asmx?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ApplicationsService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://12.118.2.172/Framework.WebService/ApplicationsService.asmx?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ApplicationsService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ApplicationsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ApplicationsService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns ApplicationsServiceSoap
     */
    @WebEndpoint(name = "ApplicationsServiceSoap")
    public ApplicationsServiceSoap getApplicationsServiceSoap() {
        return super.getPort(ApplicationsServiceSoap, ApplicationsServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ApplicationsServiceSoap
     */
//    @WebEndpoint(name = "ApplicationsServiceSoap")
//    public ApplicationsServiceSoap getApplicationsServiceSoap(WebServiceFeature... features) {
//        return super.getPort(ApplicationsServiceSoap, ApplicationsServiceSoap.class, features);
//    }
    /**
     *
     * @return
     *     returns ApplicationsServiceSoap
     */
    @WebEndpoint(name = "ApplicationsServiceSoap12")
    public ApplicationsServiceSoap getApplicationsServiceSoap12() {
        return super.getPort(ApplicationsServiceSoap12, ApplicationsServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ApplicationsServiceSoap
     */
//    @WebEndpoint(name = "ApplicationsServiceSoap12")
//    public ApplicationsServiceSoap getApplicationsServiceSoap12(WebServiceFeature... features) {
//        return super.getPort(ApplicationsServiceSoap12, ApplicationsServiceSoap.class, features);
//    }

}
